UI = {
    "WINDOW_TITLE": "File Selection",
    "TITLE": "Select Input Source",
    "DESCRIPTION": "Choose a file or directory for processing",
    "SELECTION_GROUP": "Choose Input Type",
    "FILE_ICON": "📄",
    "FILE_RADIO": "Single File",
    "DIR_ICON": "📁",
    "DIR_RADIO": "Directory",
    "FILE_SELECTION_GROUP": "Select File",
    "FILE_PATH_PLACEHOLDER": "No file selected",
    "BROWSE_FILE_BUTTON": "Browse for File...",
    "DIR_SELECTION_GROUP": "Select Directory",
    "DIR_PATH_PLACEHOLDER": "No directory selected",
    "BROWSE_DIR_BUTTON": "Browse for Directory...",
    "BATCH_GROUP": "Processing Configuration",
    "BATCH_SIZE_LABEL": "Batch Size:",
    "BATCH_SIZE_TOOLTIP": "Number of items to process in each batch",
    "CANCEL_BUTTON": "Cancel",
    "PROCESS_BUTTON": "Process",
    "PROCESSING_STARTED_TITLE": "Processing Started",
    "PROCESSING_STARTED_MSG": "Starting processing with:",
    "PATH_ERROR_TITLE": "Path Error",
    "PATH_ERROR_MSG": "The selected path does not exist or is invalid.",
}
